[language-server.ltex]
command = "ltex-ls"
config = { ltex.language = "en-NZ" }

[[language]]
name = "latex"
language-servers = [ { name = "ltex" }, { name = "texlab"}]

[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pylint.enabled = true
plugins.pyls_mypy.enabled = true
plugins.isort.enabled = true


[[language]]
name = "markdown"
language-servers = [ { name = "ltex" } ]
