format = """\
$character\
$python\
[](fg:#c678dd bg:blue)\
$directory\
[](fg:blue bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow) """

[directory]
format = "[  $path ]($style)"
style = "fg:black bg:blue"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:black bg:yellow"

[git_status]
format = '[$all_status]($style)'
style = "fg:black bg:yellow"

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
format = '$symbol'
success_symbol = '[](fg:green)[󰌽 ](bg:green fg:black)[](fg:green bg:#c678dd)'
error_symbol = '[](fg:red)[󰌽 ](bg:red fg:black)[](fg:red bg:#c678dd)'

[python]
format = "[ $symbol$virtualenv $version ]($style)"
style = "bg:#c678dd fg:black"
symbol = " "
