format = """\
[](bg:black fg:green)\
[󰌽 ](bg:green fg:black)\
[](fg:green bg:red)\
$python\
[](fg:red bg:blue)\
$directory\
[](fg:blue bg:yellow)\
$git_branch\
$git_status\
$character\
"""

[directory]
format = "[  $path ]($style)"
style = "fg:black bg:blue"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:black bg:yellow"

[git_status]
format = '[$all_status]($style)'
style = "fg:black bg:yellow"

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[](fg:yellow bg:green)[](fg:green) '
error_symbol = '[](fg:yellow bg:red)[](fg:red) '

[python]
format = "[ $symbol$virtualenv $version ]($style)"
style = "bg:red fg:black"
symbol = " "
