theme = "onedark"

[editor]
jump-label-alphabet = "aoeuidhtns"
end-of-line-diagnostics = "hint"
[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
x = "extend_line"
W = "@miw"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."+"]
d = ":pipe doq --formatter numpy"
q = ":pipe fmt -w 80 -p '#'"
s = ":sh dashit-fzf-popup"

[keys.select]
";" = ["collapse_selection", "normal_mode"]

# Same behaviour as normal mode x
x = "extend_line"

# Counterpart for normal mode V
V = "extend_to_line_end"


