theme = "onedark"

[editor]
jump-label-alphabet = "aoeuidhtns"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
x = "extend_line"
esc = ["collapse_selection", "keep_primary_selection"]
"A-," = ["goto_next_diag", ":yank-diagnostic", ":vsplit-new", "paste_clipboard_after"]

[keys.normal."+"]
d = ":pipe doq --formatter numpy"
q = ":pipe fmt -w 80 -p '#'"
g = ":sh gitu-popup"

[keys.select]
";" = ["collapse_selection", "normal_mode"]

# Same behaviour as normal mode x
x = "extend_line"

# Counterpart for normal mode V
V = "extend_to_line_end"

