[language-server.ltex]
command = "ltex-ls"
config = { ltex.language = "en-NZ" }

[[language]]
name = "latex"
language-servers = [ { name = "ltex" }, { name = "texlab"}]

[language-server.pylsp.config.pylsp]
plugins.pylint.enabled = true
plugins.pyls_mypy.enabled = true


[[language]]
name = "markdown"
language-servers = [ { name = "ltex" } ]

[[language]]
name = "haskell"
auto-format = true

[[language]]
name = "python"
language-servers = [ 'ruff', {"name" = "pylsp", except-features = ["format"]}]
auto-format = true
